import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import {Navbar, Footer} from "../components/index";

const jost = Jost({
    subsets: ["latin"],
    variable: "--font-jost",
})

export const metadata: Metadata = {
  title: "Nike Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
